# Generated by Django 3.2 on 2021-05-03 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('duration', models.FloatField(default=0)),
                ('times_played', models.IntegerField(default=0)),
                ('artist', models.URLField()),
                ('album', models.URLField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
            ],
        ),
    ]
